# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16I9z7031q7H31kRusDrReDLS32FIr1LB
"""

# from google.colab import drive
# drive.mount('/content/gdrive')

# cd "gdrive/My Drive/Bouquet"

import __init__
from MaterialNetwork import MaterialNetwork
from MappingNetwork import MappingNetwork
from SynthesizeNetwork import SynthesizeNetwork
import cv2
import numpy as np
from moviepy.editor import *

from keras import models


def main():
    # import model
    print("Downloading the Xception Model...")
    category_model = models.load_model("./model/classfier_model.h5")

    # MappingNetwork
    Mpp = MappingNetwork()
    Mpp.mapping("./material/pro_material_mp4/pro_material.mp4",category_model=category_model)

    # MaterialNetwork 
    Mtr = MaterialNetwork()

    Mtr.material("./material/material_video", init=True, category_model=category_model)

    # import map 
    mapping_json = 'mapping.json'
    fw = open(mapping_json, 'r')
    mapping = json.load(fw) # dictionary

    # map class
    map_class = np.array([mapping[k]["class"] for k in mapping.keys()]) # class of map

    # map second
    map_second = np.array( [mapping[k]["start"] for k in mapping.keys()]) 
    map_second = np.append(map_second, mapping['{}'.format(len(mapping)-1)]["stop"])/30

    # Synthsize movie
    syn = SynthesizeNetwork()

    jsonpath = "./material.json"
    syn.synthesizer(jsonpath, map_class, map_second)

if __name__ == "__main__":
    main()